# Generated by Django 2.0.7 on 2018-07-28 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(blank=True, choices=[('FROM_YASHIK_MESSAGE', 'Сообщение от ящика'), ('FROM_USER_MESSAGE', 'Сообщение от пользователя')], max_length=64, null=True)),
            ],
        ),
    ]
